### ISSUE TITLE
[Bootcamp] [Bug] Special Characters not escaped

### ISSUE THREAD

**Issue by hdavidethan** [ScottyLabs/scottylol#46]
### Expected Behavior

Search for C++ on google will input C++ to the search bar.

### Steps to Reproduce

Search C++, the search bar shows "C" instead.

This also occurs with searches with &, etc.

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.5.1
Browser Version: Chrome

**Comment by hdavidethan** [comment]
@rajgodse Possibility into turning this into a boot camp task?

**Comment by rajgodse** [comment]
Yes, let's make it a bootcamp task.

**Comment by rajgodse** [comment]
scotty.lol bootcamper: your mission, should you choose to accept it, is to modify the scotty.lol backend to appropriately process special characters included in search queries.

For example, the command `g C++` should search google for "C++", not "C", and `g H&M` should search google for "H&M", not "H".
