### ISSUE TITLE
[Bug] Special characters not escaped in search

### ISSUE THREAD

**Issue by gramliu** [ScottyLabs/scottylol#48]
### Expected Behavior

Performing a search with a special character like "&" is sent correctly to the appropriate search engine.
e.g. "g ieee s&p" should do a google search for "ieee s&p".

Instead, the "&" character is not escaped so the resulting search on google is just "ieee s"

### Steps to Reproduce

"g ieee s&p"

### Device Information

Desktop/Mobile: Desktop
OS: Windows 11
Browser Version: Microsoft Edge 105.0.1343.50

**Comment by gramliu** [comment]
Duplicate of #46

**Comment by hdavidethan** [comment]
Bug resurfaced after Next rewrite. Code in rewrite likely did not contain the most recent updates prior to merging.

**Comment by hdavidethan** [comment]
Reference: `getServerSideProps()` in `pages/search.tsx`

The value of `target` should have an encoded URI: `encodeURIComponent(query)`
